version: '3.7'

services:
  datasette:
    image: datasetteproject/datasette
    ports:
      - "8001:8001"
    volumes:
      - "./dbs:/mnt"  
    command:
      - 'datasette'
      - '-p'
      - '8001'
      - '-h'
      - '0.0.0.0'
      - '/mnt/alameda_minutes.db'
