version: '3.7'

services:
  datasette:
    image: datasetteproject/datasette
    ports:
      - "8001:8001"
    volumes:
      - "./:/mnt"
    command: datasette -p 8001 -h 0.0.0.0 --metadata /mnt/metadata.json --plugins-dir=/mnt/plugins /mnt/city_minutes.db /mnt/alameda_minutes.db